### ISSUE TITLE
Load map window buggy

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25edit#23]
The load window is currently buggy. The scroll down button is off and therefor hard to press. Also this menu could be a bit higher so more entries are shown.

![image](https://user-images.githubusercontent.com/1276342/71722000-98c6f780-2e27-11ea-815f-8697674b1e1a.png)

**Comment by Flamefire** [comment]
Like this: 
![editor](https://user-images.githubusercontent.com/309017/71725519-81423b80-2e34-11ea-9b61-e590d6e955c6.png)

**Comment by Spikeone** [comment]
Looking great
