### ISSUE TITLE
Keep file extension

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25edit#24]
Since the save dialogue has changed, one can no longer enter the file extension. Although the name is kept after loading an existing file, the ending is changed to swd.
The original file extension should be kept.

**Comment by Flamefire** [comment]
Erm, Why? IIRC SWD or WLD are not different so we can just use any and done. I don't see how a user would care or even notice

**Comment by Spikeone** [comment]
Well, as I was working on the WLD files for S2 to test them there, I had to rename them. Also I use WLD as mapformat so no one tries to just use them in settlers2 (they do not show up in freeplay). On the other hand you might be right, that I'm like the only one who dislikes the change of fileextension :D

**Comment by Flamefire** [comment]
I double checked the code: You can simply enter your extension if you want to use a specific one. It only defaults to SWD. IMO that is OK as the usecase for changing is quite limited and there is something that allows it.

**Comment by Spikeone** [comment]
But what for does it get removed anyway? Guess so you can simply rename the file. Then again how often does that happen? Maybe if you version your file by name. Well, probably doesn't matter you are right, but I quite dislike 'smart moves' which change stuff and not being able to change that behavior ;)

**Comment by Flamefire** [comment]
Because a regular user doesn't want nor need to bother with the file extension. Usually you want to give a filename and have it saved under that with the default file extension (see e.g. windows editor and pretty much all programs) If you want a specific extension you can specify it. We could make a dropdown for the file extension similar to other save dialogs, but not sure if this confuses users more than it helps.

**Comment by Spikeone** [comment]
I do understand that for new maps, but not for loaded maps - but anyway, renaming the final file, no problem I guess.

**Comment by Flamefire** [comment]
Makes sense. Done

**Comment by Spikeone** [comment]
Thanks then :)
