### ISSUE TITLE
BUG: X11/Xlib.h: No such file or directory

### ISSUE THREAD

**Issue by Flow86** [Return-To-The-Roots/s25edit#3]
Irgendwas stimmt in der cmake file noch nicht:

```
[ 97%] Building CXX object s25edit/CMakeFiles/s25edit.dir/CGame_Render.cpp.o
In file included from /usr/src/apple/s25client/s25edit/CGame_Render.cpp:9:0:
/usr/lib/apple/SDKs/MacOSX10.11.sdk/Library/Frameworks/SDL.framework/Headers/SDL_syswm.h:58:22: fatal error: X11/Xlib.h: No such file or directory
 #include <X11/Xlib.h>
                      ^
compilation terminated.
s25edit/CMakeFiles/s25edit.dir/build.make:54: recipe for target 's25edit/CMakeFiles/s25edit.dir/CGame_Render.cpp.o' failed
```

Xlib.h gibt es (im Tk.framework) - eigentlich sollte SDL die doch automatisch binden? in driver/video/SDL/src/VideoSDL.cpp ziehen wir ja auch die betroffene SDL_syswm.h ein?

**Comment by Flamefire** [comment]
Ich gehe davon aus, dass das ein system header ist, der bei MacOSX immer dabei ist. Darum sollte dafür kein extra include notwendig sein. Wo liegt denn `<X11/Xlib.h>`?

In VideoSDL wird das nur bei WIN32 eingebunden

**Comment by Flow86** [comment]
Hmm naja evtl fehlt dem SDL dann die Abhängigkeit zum TK.framework - dort sind die Header (inzwischen(?))

**Comment by Flow86** [comment]
ah X11 support "is dropped" ab Mountain Lion - darum gibts den header nur in dem extra Framework.

**Comment by Flamefire** [comment]
Sehe gerade der ist nicht nötig. Nehm ich raus.
