### ISSUE TITLE
Wasteland broken

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25edit#30]
![Wasteland](https://user-images.githubusercontent.com/1276342/102879350-e6c67800-4449-11eb-8dfa-b10472790a8f.png)

Some textures are drawn wrongly. Also water texture seems to be somewhat buggy.

**Comment by Flamefire** [comment]
Can you determine which textures are affected? The editor should now use the same data as rttr but there might be something missing

**Comment by Spikeone** [comment]
![grafik](https://user-images.githubusercontent.com/1276342/102885470-b1bf2300-4453-11eb-9f60-b62745ac9f23.png)

So 0x02, 0x03, 0x05 (guess 0x06 as well), 0x12, (guess 0x13 as well)
