### ISSUE TITLE
Resourcenfehler

### ISSUE THREAD

**Issue by Flow86** [Return-To-The-Roots/s25edit#5]
Hi,

per Email erhalten:

> wenn man mit dem Editor im Spiel selber eine Map generiert, dann gibt es
> dort einen Fehler, dass wenn man Geologen zu einem Berg sendet, dass
> diese dann dort keine Rohstoffe im Berg finden bzw der komplette Berg
> leer ist und nur leere Schilder auf dem Berg sind.

Ich habe die Karte angefordert, damit wir das einfacher nachvollziehen können

**Comment by Flow86** [comment]
Hier die Karte dazu:

![20180307_200845-min](https://user-images.githubusercontent.com/656249/37307974-dcc4b3d6-263c-11e8-9388-cf9360f6529d.jpg)
![20180307_200918-min](https://user-images.githubusercontent.com/656249/37307977-ddf94c6c-263c-11e8-92dd-8f67cb3bee30.jpg)

[Random.zip](https://github.com/Return-To-The-Roots/s25edit/files/1804454/Random.zip)

**Comment by Spikeone** [comment]
Sollte aber kein Bug im s25edit sein sondern in s25client oder? Also die Zufallskarten sind ja nicht verbunden mit dem alten neuen editor soweit ich weiß.

**Comment by Flamefire** [comment]
Jep. Ist der Editor (s25edit) gemeint, oder zufallskarte? Kann das mal jemand testen? Glaube, das ist behoben...
