### ISSUE TITLE
Near edge drawing bug

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25edit#6]
This happens if you scroll close to the edge in the latest Editor version:
![image](https://user-images.githubusercontent.com/1276342/47839120-dce8e300-ddb1-11e8-936c-9493c860d153.png)

**Comment by stefson** [comment]
The the linux port suffers the same bug, but it wasn't fixed by your efforts in df6ddfc: 

![linux](https://user-images.githubusercontent.com/14232936/51562190-8c04fa00-1e89-11e9-9425-8e45f24ab64f.jpg)

**Comment by Flamefire** [comment]
Are you 100% sure you used the latest source? I can't reproduce this after that commit.

**Comment by stefson** [comment]
oh dear, those submodules get me everytime! :-) I'll sit and wait patiently for Return-To-The-Roots/s25client#1016 to be resolved, it still fails to compile for me.
